### ISSUE TITLE
Clean up redundancy in MacroscopicEvolveM_2nd order

### ISSUE THREAD

**Issue by jackieyao0114** [RevathiJambunathan/WarpX#24]
Delete redundant lines in Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveM_2nd.cpp.

For example, the material properties are repeatedly loaded by Line 280-285, while this has been done by Line 74-80.

Note similar redundancy exists in other lines as well, such as Line 289-294. Please clean those.

**Comment by RevathiJambunathan** [comment]
@jackieyao0114 can you please add a small description for this please. which lines etc :)

**Comment by ruohai0925** [comment]
I will delete the redundant lines while dealing with PR #20.

**Comment by ruohai0925** [comment]
Done in the PR#20. We can close this issue.
